spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: true

    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: taskManager
          uri: lb://TASK-MANAGER
          predicates:
            - Path=/tasks/**
        - id: eurekaService
          uri: ${EUREKA_SERVER:http://localhost:8761}
          predicates:
            - Path=/services-status/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: ${EUREKA_SERVER:http://localhost:8761}
          predicates:
            - Path=/eureka/**
